### ISSUE TITLE
Profile Avatar

### ISSUE THREAD

**Issue by mquijom** [centralizedinc/fda-admin-portal#79] opened 2019-03-18 03:10 UTC
- **Inconsistent Avatar**

![image](https://user-images.githubusercontent.com/34019450/54504378-661e4200-496e-11e9-8e10-a23caa6e5365.png)

**Comment by abalita** [comment] 2019-03-27 09:31
- Fixed. For testing v0.1.24
- Modified file(s):
fda-admin-portal/src/views/app/accounts/profile.vue
fda-admin-portal/src/store/modules/profile_tables.js
fda-admin-portal/src/api/apiProfileManagement.js
fda-admin-portal/src/store/modules/user_session.js
fda-admin-portal/src/layout/UserLayout.vue

- Resolution: 
Implement AWS S3 image upload functionality

**Comment by VPBelo** [comment] 2019-03-28 05:02
Closing this issue.
  - Actual Result

![adminProfile](https://user-images.githubusercontent.com/34052250/55131489-c88af580-5159-11e9-84a1-59f7006cebbf.PNG)
![adminProfile2](https://user-images.githubusercontent.com/34052250/55131490-c88af580-5159-11e9-9589-54e6ada79b0a.PNG)

**Comment by VPBelo** [comment] 2019-03-28 08:11
Issue: Unable to change Profile Picture. When the page is reloaded ,the same default image appears.

![profileNew2](https://user-images.githubusercontent.com/34052250/55140903-1f9dc400-5174-11e9-995c-d11526cf404a.PNG)

**Comment by abalita** [comment] 2019-03-28 08:25
issue should already be resolved. 
Error was caused by changes in the fda-services-accounts

**Comment by VPBelo** [comment] 2019-03-28 08:27
Closing this issue.
  - Actual Result

![profileNew2](https://user-images.githubusercontent.com/34052250/55141866-4fe66200-5176-11e9-8542-24affcec40aa.PNG)

**Closed by VPBelo** 2019-03-28 08:27 UTC
Labels: enhancement, invalid
